# Generated by Django 5.0.6 on 2024-05-28 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_create_date_comment_created_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="create_date",
        ),
    ]
